#! /bin/sh
sxhkd &
xsetroot -cursor_name left_ptr
picom -b -d :0 --focus-exclude '_NET_WM_NAME@:s = "rofi"' &
wal -R &
. "${HOME}/.cache/wal/colors.sh"

#bspc monitor eDP1 -d I II III IV
#bspc monitor DP-2-2 -d V VI VII VIII
#bspc monitor -d  一   二   三   四 
#bspc monitor eDP1 -d  一   二   三   四 
#bspc monitor DP2-2 -d  五   六   七   八 
#bspc monitor DP2-1 -d  九   十 

screens="$(bspc query -M --names)"

case ${#screens[@]} in
	1) bspc monitor -d  一   二   三   四 ;;
	2)
		bspc monitor ${screens[0]} -d  一   二   三   四 
		bspc monitor ${screens[1]} -d  五   六   七   八 
		;;
	3)
		bspc monitor ${screens[0]} -d  一   二   三   四 
		bspc monitor ${screens[1]} -d  五   六   七   八 
		bspc monitor ${screens[1]} -d  九   十 
		;;
	*) bspc monitor -d  一   二   三   四 ;;
esac

bspc config border_width					8
bspc config window_gap						16
bspc config top_padding						32

bspc config split_ratio						0.50
bspc config borderless_monocle		true
bspc config gapless_monocle				true
bspc config focus_follows_pointer	true


bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color	"$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
