#! /bin/sh
sxhkd &
compton -b -d :0 --focus-exclude '_NET_WM_NAME@:s = "rofi"' &
wal -R &
/usr/bin/dunst &
. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width					8
bspc config window_gap						16

bspc config split_ratio						0.50
bspc config borderless_monocle		true
bspc config gapless_monocle				true
bspc config focus_follows_pointer	true


bspc config normal_border_color "$color0"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color	"$color1"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh &
